/*
Copyright 2022 The KubeSphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	schedulev1alpha1 "kubesphere.io/schedule/api/schedule/v1alpha1"
	versioned "kubesphere.io/schedule/pkg/client/clientset/versioned"
	internalinterfaces "kubesphere.io/schedule/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "kubesphere.io/schedule/pkg/client/listers/schedule/v1alpha1"
)

// AnalysisInformer provides access to a shared informer and lister for
// Analysises.
type AnalysisInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.AnalysisLister
}

type analysisInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewAnalysisInformer constructs a new informer for Analysis type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewAnalysisInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredAnalysisInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredAnalysisInformer constructs a new informer for Analysis type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredAnalysisInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ScheduleV1alpha1().Analysises(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ScheduleV1alpha1().Analysises(namespace).Watch(context.TODO(), options)
			},
		},
		&schedulev1alpha1.Analysis{},
		resyncPeriod,
		indexers,
	)
}

func (f *analysisInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredAnalysisInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *analysisInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&schedulev1alpha1.Analysis{}, f.defaultInformer)
}

func (f *analysisInformer) Lister() v1alpha1.AnalysisLister {
	return v1alpha1.NewAnalysisLister(f.Informer().GetIndexer())
}
