/*
Copyright 2022 The KubeSphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "kubesphere.io/scheduling/api/schedule/v1alpha1"
	scheme "kubesphere.io/scheduling/pkg/client/clientset/versioned/scheme"
)

// AnalysisTasksGetter has a method to return a AnalysisTaskInterface.
// A group's client should implement this interface.
type AnalysisTasksGetter interface {
	AnalysisTasks(namespace string) AnalysisTaskInterface
}

// AnalysisTaskInterface has methods to work with AnalysisTask resources.
type AnalysisTaskInterface interface {
	Create(ctx context.Context, analysisTask *v1alpha1.AnalysisTask, opts v1.CreateOptions) (*v1alpha1.AnalysisTask, error)
	Update(ctx context.Context, analysisTask *v1alpha1.AnalysisTask, opts v1.UpdateOptions) (*v1alpha1.AnalysisTask, error)
	UpdateStatus(ctx context.Context, analysisTask *v1alpha1.AnalysisTask, opts v1.UpdateOptions) (*v1alpha1.AnalysisTask, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.AnalysisTask, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.AnalysisTaskList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.AnalysisTask, err error)
	AnalysisTaskExpansion
}

// analysisTasks implements AnalysisTaskInterface
type analysisTasks struct {
	client rest.Interface
	ns     string
}

// newAnalysisTasks returns a AnalysisTasks
func newAnalysisTasks(c *ScheduleV1alpha1Client, namespace string) *analysisTasks {
	return &analysisTasks{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the analysisTask, and returns the corresponding analysisTask object, and an error if there is any.
func (c *analysisTasks) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.AnalysisTask, err error) {
	result = &v1alpha1.AnalysisTask{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("analysistasks").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AnalysisTasks that match those selectors.
func (c *analysisTasks) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.AnalysisTaskList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.AnalysisTaskList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("analysistasks").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested analysisTasks.
func (c *analysisTasks) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("analysistasks").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a analysisTask and creates it.  Returns the server's representation of the analysisTask, and an error, if there is any.
func (c *analysisTasks) Create(ctx context.Context, analysisTask *v1alpha1.AnalysisTask, opts v1.CreateOptions) (result *v1alpha1.AnalysisTask, err error) {
	result = &v1alpha1.AnalysisTask{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("analysistasks").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(analysisTask).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a analysisTask and updates it. Returns the server's representation of the analysisTask, and an error, if there is any.
func (c *analysisTasks) Update(ctx context.Context, analysisTask *v1alpha1.AnalysisTask, opts v1.UpdateOptions) (result *v1alpha1.AnalysisTask, err error) {
	result = &v1alpha1.AnalysisTask{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("analysistasks").
		Name(analysisTask.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(analysisTask).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *analysisTasks) UpdateStatus(ctx context.Context, analysisTask *v1alpha1.AnalysisTask, opts v1.UpdateOptions) (result *v1alpha1.AnalysisTask, err error) {
	result = &v1alpha1.AnalysisTask{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("analysistasks").
		Name(analysisTask.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(analysisTask).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the analysisTask and deletes it. Returns an error if one occurs.
func (c *analysisTasks) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("analysistasks").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *analysisTasks) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("analysistasks").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched analysisTask.
func (c *analysisTasks) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.AnalysisTask, err error) {
	result = &v1alpha1.AnalysisTask{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("analysistasks").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
